/**
 * sprites.mjs — АЛЬБОМ ХУДОЖНИКА
 * ------------------------------------------------------------------
 * Всё живое и вещественное в игре нарисовано здесь пиксель в пиксель.
 * Эмодзи не годятся: они цветные, гладкие и разные на каждой платформе,
 * а нам нужна одна пропитая ромом таверна на всех.
 *
 * Портреты — 24×24, по два кадра: моряки покачиваются и моргают.
 * Реквизит — 16×16. Огонь и фонарь — ленты по три кадра.
 *
 * Палитра одна на всех, иначе рожи и утварь разъезжаются по стилю:
 *   k обводка      d тень
 *   o/O орочья зелень       c/C мурлочья бирюза
 *   y/Y гоблинская охра     p/P тролличий пурпур
 *   b/B кость               n румянец пьяницы
 *   r/R красное сукно       g/G золото       a/A латунь
 *   w/W дерево              s/S сталь        v/V бутылочное стекло
 *   f/F/e огонь             t тёмная кожа
 */

export const PALETTE = {
  '.': null,
  k: [10, 16, 20],
  d: [28, 40, 46],
  t: [58, 42, 30],
  o: [72, 120, 52], O: [120, 176, 74],
  c: [46, 122, 92], C: [108, 196, 118],
  y: [156, 124, 42], Y: [216, 178, 70],
  p: [108, 76, 154], P: [162, 124, 212],
  b: [206, 190, 152], B: [246, 238, 214],
  n: [196, 96, 76],
  r: [162, 42, 34], R: [214, 74, 58],
  g: [202, 156, 46], G: [255, 226, 132],
  a: [150, 108, 44], A: [212, 168, 74],
  w: [96, 64, 32], W: [142, 102, 56],
  s: [104, 120, 128], S: [178, 192, 200],
  v: [46, 96, 62], V: [96, 154, 96],
  f: [204, 72, 20], F: [255, 152, 42], e: [255, 238, 158],
}

/* ═══════════════════ ПОРТРЕТЫ 24×24 ═══════════════════
   Кадр «спокойный» и кадр «качнулся»: моряк дышит, моргает
   и слегка ведёт головой — от рома. */

const ORC_A = [
  '........................',
  '........................',
  '.......kkkkkkkkkk.......',
  '......kOOOOOOOOOOk......',
  '.....kOOOOOOOOOOOOk.....',
  '.....kOOOOOOOOOOOOk.....',
  '.....kkkkOOOOkkkkOk.....',
  '.....kOkkOOOOkkOOOk.....',
  '.....kOkkOOOOkkOOOk.....',
  '.....kOOOOOOOOOOOOk.....',
  '.....kOOOnnnnOOOOOk.....',
  '.....kOOOnnnnOOOOOk.....',
  '.....kOOkkkkkkkkOOk.....',
  '.....kObkOOOOOOkbOk.....',
  '.....kObkkkkkkkkbOk.....',
  '.....kOOOOOOOOOOOOk.....',
  '......kOOOOOOOOOOk......',
  '.......kkkkkkkkkk.......',
  '....kkkwwwwwwwwwwkkk....',
  '...kwwwwwwwwwwwwwwwwk...',
  '...kwWWwwwwwwwwwwWWwk...',
  '...kwwwwwwwwwwwwwwwwk...',
  '...kkkkkkkkkkkkkkkkkk...',
  '........................',
]
const ORC_B = [
  '........................',
  '........................',
  '.......kkkkkkkkkk.......',
  '......kOOOOOOOOOOk......',
  '.....kOOOOOOOOOOOOk.....',
  '.....kOOOOOOOOOOOOk.....',
  '.....kkkkkkkkkkkkOk.....',
  '.....kOOOOOOOOOOOOk.....',
  '.....kOOOOOOOOOOOOk.....',
  '.....kOOOOOOOOOOOOk.....',
  '.....kOOOnnnnOOOOOk.....',
  '.....kOOOnnnnOOOOOk.....',
  '.....kOOkkkkkkkkOOk.....',
  '.....kObkOOOOOOkbOk.....',
  '.....kObkkkkkkkkbOk.....',
  '.....kOOOOOOOOOOOOk.....',
  '......kOOOOOOOOOOk......',
  '.......kkkkkkkkkk.......',
  '....kkkwwwwwwwwwwkkk....',
  '...kwwwwwwwwwwwwwwwwk...',
  '...kwWWwwwwwwwwwwWWwk...',
  '...kwwwwwwwwwwwwwwwwk...',
  '...kkkkkkkkkkkkkkkkkk...',
  '........................',
]

const MURLOC_A = [
  '........................',
  '..........kk............',
  '.........kCCk...........',
  '........kCCCCk..........',
  '...kk...kCCCCk...kk.....',
  '..kCCk.kCCCCCCk.kCCk....',
  '..kCCkkCCCCCCCCkkCCk....',
  '..kCCCCCCCCCCCCCCCCk....',
  '..kCBBkCCCCCCCCkBBCk....',
  '..kCBkkCCCCCCCCkkBCk....',
  '..kCCCCCCCnnCCCCCCCk....',
  '..kCCCCCCCnnCCCCCCCk....',
  '...kCCbbbbbbbbbbCCk.....',
  '...kCbkbkbkbkbkbCCk.....',
  '...kCCbbbbbbbbbbCCk.....',
  '....kCCCCCCCCCCCCk......',
  '.....kkCCCCCCCCkk.......',
  '.......kkkkkkkk.........',
  '....kkkvvvvvvvvkkk......',
  '...kvvvvvvvvvvvvvvk.....',
  '...kvVVvvvvvvvvVVvk.....',
  '...kvvvvvvvvvvvvvvk.....',
  '...kkkkkkkkkkkkkkkk.....',
  '........................',
]
const MURLOC_B = [
  '........................',
  '..........kk............',
  '.........kCCk...........',
  '........kCCCCk..........',
  '..kk....kCCCCk....kk....',
  '.kCCk..kCCCCCCk..kCCk...',
  '.kCCkkkCCCCCCCCkkkCCk...',
  '..kCCCCCCCCCCCCCCCCk....',
  '..kCkkkCCCCCCCCkkkCk....',
  '..kCCCCCCCCCCCCCCCCk....',
  '..kCCCCCCCnnCCCCCCCk....',
  '..kCCCCCCCnnCCCCCCCk....',
  '...kCCbbbbbbbbbbCCk.....',
  '...kCbkbkbkbkbkbCCk.....',
  '...kCCbbbbbbbbbbCCk.....',
  '....kCCCCCCCCCCCCk......',
  '.....kkCCCCCCCCkk.......',
  '.......kkkkkkkk.........',
  '....kkkvvvvvvvvkkk......',
  '...kvvvvvvvvvvvvvvk.....',
  '...kvVVvvvvvvvvVVvk.....',
  '...kvvvvvvvvvvvvvvk.....',
  '...kkkkkkkkkkkkkkkk.....',
  '........................',
]

const GOBLIN_A = [
  '........................',
  '........................',
  '........kkkkkkkk........',
  '.kk....kYYYYYYYYk....kk.',
  '.kYk..kYYYYYYYYYYk..kYk.',
  '.kYYkkYYYYYYYYYYYYkkYYk.',
  '..kYYYYkkYYYYkkYYYYYYk..',
  '...kYYYkkYYYYkkYYYYYk...',
  '....kYYYYYYYYYYYYYYk....',
  '......kYYYYnnYYYYYk.....',
  '......kYYYYnnYYYYYk.....',
  '.......kYYYnnYYYYk......',
  '.......kYYYnnYYYYk......',
  '.......kYbbbbbbYk.......',
  '.......kYbkkkkbYk.......',
  '........kYYYYYYk........',
  '.........kkkkkk.........',
  '.....kkkaaaaaaaakkk.....',
  '....kaaaaaaaaaaaaaak....',
  '....kaAAaaaaaaaaAAak....',
  '....kaaaaaaaaaaaaaak....',
  '....kkkkkkkkkkkkkkkk....',
  '........................',
  '........................',
]
const GOBLIN_B = [
  '........................',
  '........................',
  '........kkkkkkkk........',
  '.kk....kYYYYYYYYk....kk.',
  '.kYk..kYYYYYYYYYYk..kYk.',
  '.kYYkkYYYYYYYYYYYYkkYYk.',
  '..kYYYYYYYYYYYYYYYYYYk..',
  '...kYYYkkYYYYkkYYYYYk...',
  '....kYYYYYYYYYYYYYYk....',
  '......kYYYYnnYYYYYk.....',
  '......kYYYYnnYYYYYk.....',
  '.......kYYYnnYYYYk......',
  '.......kYYYnnYYYYk......',
  '.......kYbbbbbbYk.......',
  '.......kYbkkkkbYk.......',
  '........kYYYYYYk........',
  '.........kkkkkk.........',
  '.....kkkaaaaaaaakkk.....',
  '....kaaaaaaaaaaaaaak....',
  '....kaAAaaaaaaaaAAak....',
  '....kaaaaaaaaaaaaaak....',
  '....kkkkkkkkkkkkkkkk....',
  '........................',
  '........................',
]

const TROLL_A = [
  '........................',
  '......kkkkkkkkkkkk......',
  '.....krrrrrrrrrrrrk.....',
  '....krRRrrrrrrrrRRrk....',
  '....krrrrrrrrrrrrrrk....',
  '....kkkkkkkkkkkkkkkk....',
  '.....kPPPPPPPPPPPPk.....',
  '.....kPkkPPPPPPkkPk.....',
  '.....kPkkPPPPPPkkPk.....',
  '....gkPPPPPPPPPPPPk.....',
  '....gkPPPPnnPPPPPPk.....',
  '....gkPPPPnnPPPPPPk.....',
  '.....kPPbbbbbbbbPPk.....',
  '.....kPbkkkkkkkkbPk.....',
  '.....kPPbPPPPPPbPPk.....',
  '.....kPPPPPPPPPPPPk.....',
  '......kkkkkkkkkkkk......',
  '....kkkttttttttttkkk....',
  '...kttttttttttttttttk...',
  '...ktTTttttttttttTTtk...'.replace(/T/g, 'S'),
  '...kttttttttttttttttk...',
  '...kkkkkkkkkkkkkkkkkk...',
  '........................',
  '........................',
]
const TROLL_B = [
  '........................',
  '......kkkkkkkkkkkk......',
  '.....krrrrrrrrrrrrk.....',
  '....krRRrrrrrrrrRRrk....',
  '....krrrrrrrrrrrrrrk....',
  '....kkkkkkkkkkkkkkkk....',
  '.....kPPPPPPPPPPPPk.....',
  '.....kPPPPPPPPPPPPk.....',
  '.....kPkkPPPPPPkkPk.....',
  '....gkPPPPPPPPPPPPk.....',
  '....gkPPPPnnPPPPPPk.....',
  '....gkPPPPnnPPPPPPk.....',
  '.....kPPbbbbbbbbPPk.....',
  '.....kPbkkkkkkkkbPk.....',
  '.....kPPbPPPPPPbPPk.....',
  '.....kPPPPPPPPPPPPk.....',
  '......kkkkkkkkkkkk......',
  '....kkkttttttttttkkk....',
  '...kttttttttttttttttk...',
  '...ktSSttttttttttSStk...',
  '...kttttttttttttttttk...',
  '...kkkkkkkkkkkkkkkkkk...',
  '........................',
  '........................',
]

export const BUSTS = {
  orc: [ORC_A, ORC_B],
  murloc: [MURLOC_A, MURLOC_B],
  goblin: [GOBLIN_A, GOBLIN_B],
  troll: [TROLL_A, TROLL_B],
}

/* ═══════════════════ РЕКВИЗИТ 16×16 ═══════════════════ */

export const PROPS = {
  // Кружка рома с пеной
  mug: [
    '................',
    '................',
    '..kkkkkkkk......',
    '..kBBBBBBk......',
    '..kBBBBBBkkkk...',
    '..kwWWWWwkWWk...',
    '..kwWWWWwkkWk...',
    '..kwWWWWwk.Wk...',
    '..kwWWWWwk.Wk...',
    '..kwWWWWwkkWk...',
    '..kwWWWWwkWWk...',
    '..kwwwwwwkkkk...',
    '..kkkkkkkk......',
    '................',
    '................',
    '................',
  ],
  // Бутыль рома с пробкой
  bottle: [
    '................',
    '......kkk.......',
    '......kwk.......',
    '......kvk.......',
    '......kvk.......',
    '.....kvvvk......',
    '....kvVVVvk.....',
    '....kvVVVvk.....',
    '....kvVVVvk.....',
    '....kvVbbvk.....',
    '....kvVbbvk.....',
    '....kvVVVvk.....',
    '....kvvvvvk.....',
    '....kkkkkkk.....',
    '................',
    '................',
  ],
  // Фонарь
  lantern: [
    '.......kk.......',
    '......kaak......',
    '.....ka..ak.....',
    '....kkaaaakk....',
    '....kSSSSSSk....',
    '...kSeFFFFeSk...',
    '...kSeFFFFeSk...',
    '...kSeFFFFeSk...',
    '...kSeeFFeeSk...',
    '...kSSSSSSSSk...',
    '....kaaaaaak....',
    '.....kkkkkk.....',
    '................',
    '................',
    '................',
    '................',
  ],
  // Попугай
  parrot: [
    '................',
    '.....kkk........',
    '....kRRRk.......',
    '...kRRRRRk.g....',
    '...kRkRRRkgk....',
    '...kRRRRRk.g....',
    '..kRRRRRRRk.....',
    '..kRRvvvRRk.....',
    '..kRRvvvRRk.....',
    '..kRRRRRRRk.....',
    '...kRRRRRk......',
    '....kgggk.......',
    '.....kgk........',
    '.....kkk........',
    '................',
    '................',
  ],
  // Краб
  crab: [
    '................',
    '..k..........k..',
    '.kRk........kRk.',
    '.kRRk.kkkk.kRRk.',
    '.kRRkkrrrrkkRRk.',
    '..krrrrrrrrrrk..',
    '..krBrrrrrrBrk..',
    '..krrrrrrrrrrk..',
    '..kRrrrrrrrrRk..',
    '..krrrrrrrrrrk..',
    '.rrk.r.rr.r.krr.',
    'r..r.r.rr.r.r..r',
    '................',
    '................',
    '................',
    '................',
  ],
  // Якорь
  anchor: [
    '.......kk.......',
    '......kSSk......',
    '......kkkk......',
    '.......SS.......',
    '....kkkSSkkk....',
    '....kSSSSSSk....',
    '.......SS.......',
    '.......SS.......',
    '.k.....SS.....k.',
    'kSk....SS....kSk',
    'kSSk...SS...kSSk',
    '.kSSkkkSSkkkSSk.',
    '..kSSSSSSSSSSk..',
    '...kkSSSSSSkk...',
    '.....kkkkkk.....',
    '................',
  ],
  // Бочка
  barrel: [
    '................',
    '..kkkkkkkkkkk...',
    '..kwWWWWWWWwk...',
    '..kaaaaaaaaak...',
    '..kwWwWWWwWwk...',
    '..kwWwWWWwWwk...',
    '..kwWwWWWwWwk...',
    '..kaaaaaaaaak...',
    '..kwWwWWWwWwk...',
    '..kwWwWWWwWwk...',
    '..kwWwWWWwWwk...',
    '..kaaaaaaaaak...',
    '..kwWWWWWWWwk...',
    '..kkkkkkkkkkk...',
    '................',
    '................',
  ],
  // Рыба-пила: трофей, которым хвастается хозяин
  sawfish: [
    '................................',
    '..S.S.S.S.S.........kk..........',
    '.SSSSSSSSSSS.......kCCk.........',
    '.SssssssssssS......kCCCk........',
    '.SSSSSSSSSSSSkkkkkkkCCCCkk.kk...',
    '..S.S.S.S.S.kCCCCCCCCCCCCCCkCCCk',
    '............kCBCCCCCCCCCCCCCCCCk',
    '............kCCCCCCCCCCCCCCCCCCk',
    '............kCCCCCCCCCCCCCCCCCk.',
    '............kkCCCCCCCCCCCCCCkk..',
    '.............kkCCCCCCCCCCkk.....',
    '...............kkkCCCkkk........',
    '..................kk............',
    '................................',
    '................................',
    '................................',
  ],
  // Рыба
  fish: [
    '................',
    '................',
    '................',
    '.........kk.....',
    '...kkkk.kCk.....',
    '..kCCCCkkCCk....',
    '.kCkCCCCCCCCk...',
    '.kCCCCCCCCCCk...',
    '.kCkCCCCCCCCk...',
    '..kCCCCkkCCk....',
    '...kkkk.kCk.....',
    '.........kk.....',
    '................',
    '................',
    '................',
    '................',
  ],
  // Кость
  die: [
    '................',
    '..kkkkkkkkkkk...',
    '..kBBBBBBBBBk...',
    '..kBkkBBBkkBk...',
    '..kBkkBBBkkBk...',
    '..kBBBBBBBBBk...',
    '..kBBBkkkBBBk...',
    '..kBBBkkkBBBk...',
    '..kBBBBBBBBBk...',
    '..kBkkBBBkkBk...',
    '..kBkkBBBkkBk...',
    '..kBBBBBBBBBk...',
    '..kkkkkkkkkkk...',
    '................',
    '................',
    '................',
  ],
  // Череп
  skull: [
    '................',
    '....kkkkkk......',
    '...kBBBBBBk.....',
    '..kBBBBBBBBk....',
    '..kBkkBBkkBk....',
    '..kBkkBBkkBk....',
    '..kBBBBBBBBk....',
    '..kBBBkkBBBk....',
    '...kBBBBBBk.....',
    '...kBkbkbkBk....',
    '...kkkkkkkk.....',
    '................',
    '................',
    '................',
    '................',
    '................',
  ],
  // Звук включён
  sound: [
    '................',
    '................',
    '......kk........',
    '.....kSk..k.....',
    '....kSSk.kSk....',
    '..kkSSSk.kSk.k..',
    '..kSSSSk..kSkSk.',
    '..kSSSSk..kSkSk.',
    '..kkSSSk.kSk.k..',
    '....kSSk.kSk....',
    '.....kSk..k.....',
    '......kk........',
    '................',
    '................',
    '................',
    '................',
  ],
  // Звук выключен
  mute: [
    '................',
    '................',
    '......kk........',
    '.....kSk........',
    '....kSSk.k...k..',
    '..kkSSSk..k.k...',
    '..kSSSSk...k....',
    '..kSSSSk..k.k...',
    '..kkSSSk.k...k..',
    '....kSSk........',
    '.....kSk........',
    '......kk........',
    '................',
    '................',
    '................',
    '................',
  ],
}

/* ═══════════════════ ОЧАГ: три кадра ═══════════════════ */

export const FIRE_FRAMES = [
  [
    '................',
    '................',
    '.......e........',
    '......eFe.......',
    '.....eFFFe......',
    '.....FFFFF......',
    '....fFFFFFf.....',
    '....fFFeFFf.....',
    '...ffFFeFFff....',
    '...ffFFFFFff....',
    '..fffFFFFFfff...',
    '..ffffFFFffff...',
    '..wwwwwwwwwww...',
    '..kwWwwWwwWwk...',
    '..kkkkkkkkkkk...',
    '................',
  ],
  [
    '................',
    '................',
    '........e.......',
    '.......eFe......',
    '......eFFFe.....',
    '.....eFFFFe.....',
    '....fFFFFFf.....',
    '....fFFeFFf.....',
    '...ffFeeFFf.....',
    '...ffFFFFFff....',
    '..fffFFFFFff....',
    '..ffffFFFffff...',
    '..wwwwwwwwwww...',
    '..kwWwwWwwWwk...',
    '..kkkkkkkkkkk...',
    '................',
  ],
  [
    '................',
    '................',
    '......e.........',
    '.....eFe........',
    '.....FFFe.......',
    '....eFFFFe......',
    '....fFFFFf......',
    '...ffFeFFf......',
    '...ffFeeFFf.....',
    '..fffFFFFFf.....',
    '..fffFFFFFff....',
    '..ffffFFFffff...',
    '..wwwwwwwwwww...',
    '..kwWwwWwwWwk...',
    '..kkkkkkkkkkk...',
    '................',
  ],
]
